import type { Metadata } from 'next'
import { Press_Start_2P as PressStart2P, VT323 } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { Container } from '@/components/Container'

const pressStart2P = PressStart2P({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--display-font',
})

const vt323 = VT323({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--body-font',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={`${pressStart2P.variable} ${vt323.variable}`}>
      <body>
        <Providers>
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  )
}
